[build]
  publish = "."
  functions = "netlify/functions"
  command = "echo 'Static site - no build required'"

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"
  SECRETS_SCAN_ENABLED = "false"

[context.production.environment]
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"
  SECRETS_SCAN_ENABLED = "false"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

