[build]
  publish = "."
  functions = "netlify/functions"

# Optional: redirect root-level 404s to a simple 404 if present
#[[redirects]]
#  from = "/*"
#  to = "/404.html"
#  status = 404

[functions]
  node_bundler = "esbuild"

[build]
  functions = "netlify/functions"
  publish = "."

[build.environment]
  NODE_VERSION = "18"
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
