[build]
  functions = "netlify/functions"
  publish = "."

[build.environment]
  NODE_VERSION = "18"
  SECRETS_SCAN_SMART_DETECTION_OMIT_VALUES = "AIza***"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
